# This script writes the metadata generated by download_recount3.R to a tsv

library(dplyr)
library(tibble)

if (rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
} else{
  # If running as a script, finding the file is harder
  # https://stackoverflow.com/a/55322344/10930590
  this_file <- commandArgs() %>% 
    tibble::enframe(name = NULL) %>%
    tidyr::separate(col=value, into=c("key", "value"), sep="=", fill='right') %>%
    dplyr::filter(key == "--file") %>%
    dplyr::pull(value)
  
  setwd(dirname(this_file))
}

metadata_path <- '../data/metadata_df.rda'
out_file <- '../data/recount_metadata.tsv'

load(metadata_path)

write.table(metadata_df, file=out_file, col.names=TRUE, sep='\t', )
