"""Reorder recount data to make the genes match the GTEx data"""

import argparse

import pandas as pd

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('recount_file', help='The file containing the count matrix generated by '
                                             'normalize_recount_gtex_genes')
    parser.add_argument('gtex_file', help='The file containing the GTEx expression data to '
                                          'be used in training')
    parser.add_argument('out_file', help='The location to store the results')
    args = parser.parse_args()

    recount_df = pd.read_csv(args.recount_file, sep='\t')

    gtex_header = pd.read_csv(args.gtex_file, sep='\t', nrows=1, header=0)
    gtex_header = gtex_header.rename({'Unnamed: 0': 'sample'}, axis='columns').columns

    reordered_df = recount_df[gtex_header]
    reordered_df = reordered_df.set_index('sample')

    reordered_df.to_csv(args.out_file, sep='\t')
